CREATE TABLE %dbpre%matches (
  gm_num INTEGER PRIMARY KEY,
  gm_server smallint(5) NOT NULL default 0,
  gm_serverversion varchar(10) NOT NULL default '',
  gm_map mediumint(8) NOT NULL default 0,
  gm_type tinyint(3) NOT NULL default 0,
  gm_uttype tinyint(1) NOT NULL default 0,
  gm_init datetime NOT NULL default '0000-00-00 00:00:00',
  gm_start datetime NOT NULL default '0000-00-00 00:00:00',
  gm_logger tinyint(3) NOT NULL default 0,
  gm_logname varchar(45) NOT NULL default '',
  gm_rpg tinyint(1) NOT NULL default 0,
  gm_maxwave smallint(5) NOT NULL default 0,
  gm_difficulty tinyint(1) NOT NULL default 0,
  gm_mutators varchar(255) default NULL,
  gm_mapvoting tinyint(1) NOT NULL default 0,
  gm_kickvoting tinyint(1) NOT NULL default 0,
  gm_fraglimit smallint(5) NOT NULL default 0,
  gm_timelimit smallint(5) NOT NULL default 0,
  gm_overtime smallint(5) NOT NULL default 0,
  gm_minplayers tinyint(3) NOT NULL default 0,
  gm_translocator tinyint(1) NOT NULL default 0,
  gm_endtimedelay float NOT NULL default 0,
  gm_balanceteams smallint(1) NOT NULL default 0,
  gm_playersbalanceteams smallint(1) NOT NULL default 0,
  gm_friendlyfirescale varchar(10) NOT NULL default '',
  gm_linksetup varchar(26) NOT NULL default '',
  gm_gamespeed float NOT NULL default 0,
  gm_healthforkills tinyint(1) NOT NULL default 0,
  gm_allowsuperweapons tinyint(1) NOT NULL default 1,
  gm_camperalarm tinyint(1) NOT NULL default 0,
  gm_allowpickups tinyint(1) NOT NULL default 1,
  gm_allowadrenaline tinyint(1) NOT NULL default 1,
  gm_fullammo tinyint(1) NOT NULL default 0,
  gm_starttime bigint(19) NOT NULL default 0,
  gm_length bigint(19) NOT NULL default 0,
  gm_numplayers smallint(5) NOT NULL default 0,
  gm_kills smallint(5) NOT NULL default 0,
  gm_deaths smallint(5) NOT NULL default 0,
  gm_suicides smallint(5) NOT NULL default 0,
  gm_numteams tinyint(1) NOT NULL default 0,
  gm_tscore0 smallint(6) NOT NULL default 0,
  gm_tscore1 smallint(6) NOT NULL default 0,
  gm_tscore2 smallint(6) NOT NULL default 0,
  gm_tscore3 smallint(6) NOT NULL default 0,
  gm_firstblood smallint(6) NOT NULL default -1,
  gm_headshots smallint(5) NOT NULL default 0,
  gm_status tinyint(1) NOT NULL default 0
);

CREATE INDEX gm_gstart ON %dbpre%matches (gm_start);
CREATE INDEX gm_svnum ON %dbpre%matches (gm_server,gm_num);
CREATE INDEX gm_svmap ON %dbpre%matches (gm_server,gm_map);
CREATE INDEX gm_mapnum ON %dbpre%matches (gm_map,gm_num);
